spring:
  application:
    environment: production

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
    com.uguimar: ${LOG_LEVEL_APP:INFO}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:WARN}
    org.springframework.data.r2dbc: ${LOG_LEVEL_R2DBC:WARN}
    org.springframework.cloud: ${LOG_LEVEL_SPRING_CLOUD:WARN}
    reactor.netty: ${LOG_LEVEL_REACTOR:WARN}

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:"health,info,prometheus"}
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS:when_authorized}
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}
  tracing:
    sampling:
      probability: ${TRACING_PROBABILITY:0.1}

cors:
  allowed-origins: ${CORS_ORIGINS:"https://api.uguimar.com,https://admin.uguimar.com"}
  allowed-methods: ${CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_HEADERS:"Origin,Content-Type,Accept,Authorization"}
  max-age: ${CORS_MAX_AGE:3600}

server:
  error:
    include-message: ${ERROR_INCLUDE_MESSAGE:never}
    include-binding-errors: ${ERROR_INCLUDE_BINDING:never}
