spring:
  application:
    environment: production

logging:
  level:
    root: WARN
    com.yobel: INFO
    org.springframework.web: WARN
    org.springframework.data.r2dbc: WARN
    org.springframework.cloud: WARN
    reactor.netty: WARN

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
        probability: 0.1

cors:
  allowed-origins: "https://api.yobel.com,https://admin.yobel.com"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "Origin,Content-Type,Accept,Authorization"
  max-age: 3600

server:
  error:
    include-message: never
    include-binding-errors: never